language: python
python:
  - "2.7"
install:
  - "pip install -r requirements_tests.txt"
  - "pip install lxml"
  - "python setup.py develop"
before_script:
  - "pip install python-coveralls --use-mirrors"
script:
  - "nosetests --with-doctest"
after_success:
  - "coveralls"