language: python
python:
  - "2.7"
install:
  - "pip install nose nose-parameterized nose-cov"
  - "pip install lxml"
  - "pip install python-coveralls"
  - "python setup.py develop"
script:
  - "nosetests --with-cov --cover-erase --cov"
after_success:
  - "coveralls"